### ISSUE TITLE
Add a language file to easily change the texts

### ISSUE THREAD

**Issue by heyitslumi** [HolaClient/X#18]
I seen a lot of "spelling mistakes", but it's hard to go to individual files just to edit the entire dashboard. This would probably also help people fully translate the dashboard to their own language instead of English. My guess is that it won't really be added  but eh

**Comment by recabasic** [comment]
Sure!

**Comment by recabasic** [comment]
done!

**Comment by heyitslumi** [comment]
> done!

wer pull request
