### ISSUE TITLE
Estimated date for HolaClient V2?

### ISSUE THREAD

**Issue by alessiodam** [HolaClient/X#46]
Hello,
I am starting a game hosting company and I need a user panel where people can register, pay, etc.. I've found this which is apparently a very great panel, but as you may know, it's in EOL 😅.
When do you think V2 will come out 👀 thanks! :)

**Comment by recabasic** [comment]
Greetings @tkbstudios ,
Great to hear from you about this issue, I am sorry to tell you that It'll take two more months for the release of v2. Currently I am working on HolaClientX which is basically a supported version of v1 series, It is expected to release in a week.
Thanks.

**Comment by BeastGamer81** [comment]
Use KlovitClient,

**Comment by privt00** [comment]
Use tfc plex has more stars then klovit

**Comment by BeastGamer81** [comment]
> Use tfc plex has more stars then klovit

Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.

**Comment by recabasic** [comment]
both are crap imo

**Comment by BeastGamer81** [comment]
> both are crap imo

How tho?
KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.

**Comment by privt00** [comment]
> > Use tfc plex has more stars then klovit
> 
> Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.

Ok so why you dont do

**Comment by BeastGamer81** [comment]
> > > Use tfc plex has more stars then klovit
> > 
> > 
> > Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.
> 
> Ok so why you dont do

It's against my ethics to skid some code from someone else's hardwork.

**Comment by recabasic** [comment]
> > both are crap imo
> 
> How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.

HolaClientX has 0ms loadtime.

**Comment by recabasic** [comment]
> > > Use tfc plex has more stars then klovit
> > 
> > 
> > Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.
> 
> Ok so why you dont do

This comment could end up being sued for encouraging theft & abuse of license.

**Comment by BeastGamer81** [comment]
> > > both are crap imo
> > 
> > 
> > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> 
> HolaClientX has 0ms loadtime.

While fetching 2k Pterodactyl accounts?

**Comment by recabasic** [comment]
> > > > both are crap imo
> > > 
> > > 
> > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > 
> > 
> > HolaClientX has 0ms loadtime.
> 
> While fetching 2k Pterodactyl accounts?

Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?

**Comment by BeastGamer81** [comment]
> > > > > both are crap imo
> > > > 
> > > > 
> > > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > > 
> > > 
> > > HolaClientX has 0ms loadtime.
> > 
> > 
> > While fetching 2k Pterodactyl accounts?
> 
> Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?

To benchmark it, and obv to flex the user count and it fetches everything and makes a dropdown menu (A feature from V0.9)

**Comment by recabasic** [comment]
> > > > > > both are crap imo
> > > > > 
> > > > > 
> > > > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > > > 
> > > > 
> > > > HolaClientX has 0ms loadtime.
> > > 
> > > 
> > > While fetching 2k Pterodactyl accounts?
> > 
> > 
> > Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?
> 
> To benchmark it, and obv to flex the user count and it fetches everything and makes a dropdown menu (A feature from V0.9)

Well I do that in the admin routes only. Takes about 20-60ms. >2 ms if users table has less than 5 users.

**Comment by BeastGamer81** [comment]
> > > > > > > both are crap imo
> > > > > > 
> > > > > > 
> > > > > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > > > > 
> > > > > 
> > > > > HolaClientX has 0ms loadtime.
> > > > 
> > > > 
> > > > While fetching 2k Pterodactyl accounts?
> > > 
> > > 
> > > Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?
> > 
> > 
> > To benchmark it, and obv to flex the user count and it fetches everything and makes a dropdown menu (A feature from V0.9)
> 
> Well I do that in the admin routes only. Takes about 20-60ms. >2 ms if users table has less than 5 users.

Who said that I do it on Users' routes? and your Client is 20x slower than KC V0.5

**Comment by privt00** [comment]
> > > > Use tfc plex has more stars then klovit
> > > 
> > > 
> > > Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.
> > 
> > 
> > Ok so why you dont do
> 
> It's against my ethics to skid some code from someone else's hardwork.

Ritz sayd you use his theme in 0.3 and all

**Comment by BeastGamer81** [comment]
> > > > > Use tfc plex has more stars then klovit
> > > > 
> > > > 
> > > > Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.
> > > 
> > > 
> > > Ok so why you dont do
> > 
> > 
> > It's against my ethics to skid some code from someone else's hardwork.
> 
> Ritz sayd you use his theme in 0.3 and all

His theme? CR072 gave me permit to use "HIS" theme in versions >=V0.3. That Rizz guy is a complete liar.

**Comment by recabasic** [comment]
> > > > > > > > both are crap imo
> > > > > > > 
> > > > > > > 
> > > > > > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > > > > > 
> > > > > > 
> > > > > > HolaClientX has 0ms loadtime.
> > > > > 
> > > > > 
> > > > > While fetching 2k Pterodactyl accounts?
> > > > 
> > > > 
> > > > Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?
> > > 
> > > 
> > > To benchmark it, and obv to flex the user count and it fetches everything and makes a dropdown menu (A feature from V0.9)
> > 
> > 
> > Well I do that in the admin routes only. Takes about 20-60ms. >2 ms if users table has less than 5 users.
> 
> Who said that I do it on Users' routes? and your Client is 20x slower than KC V0.5

I never released HolaClientX publicly, check the #updates if you don't trust.

**Comment by recabasic** [comment]
> > > > > Use tfc plex has more stars then klovit
> > > > 
> > > > 
> > > > Because I don't go and beg anyone to star my Client Panel and I code stuff myself not skidding HolaClient like you.
> > > 
> > > 
> > > Ok so why you dont do
> > 
> > 
> > It's against my ethics to skid some code from someone else's hardwork.
> 
> Ritz sayd you use his theme in 0.3 and all

It was an unfinished theme.

**Comment by BeastGamer81** [comment]
> > > > > > > > > both are crap imo
> > > > > > > > 
> > > > > > > > 
> > > > > > > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > > > > > > 
> > > > > > > 
> > > > > > > HolaClientX has 0ms loadtime.
> > > > > > 
> > > > > > 
> > > > > > While fetching 2k Pterodactyl accounts?
> > > > > 
> > > > > 
> > > > > Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?
> > > > 
> > > > 
> > > > To benchmark it, and obv to flex the user count and it fetches everything and makes a dropdown menu (A feature from V0.9)
> > > 
> > > 
> > > Well I do that in the admin routes only. Takes about 20-60ms. >2 ms if users table has less than 5 users.
> > 
> > 
> > Who said that I do it on Users' routes? and your Client is 20x slower than KC V0.5
> 
> I never released HolaClientX publicly, check the #updates if you don't trust.

I made the calculations based on your answer a few comments up.

**Comment by recabasic** [comment]
> > > > > > > > > > both are crap imo
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > How tho? KlovitClient V0.5 will be made in the world's fastest framework which does everything in less than 1ms.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > HolaClientX has 0ms loadtime.
> > > > > > > 
> > > > > > > 
> > > > > > > While fetching 2k Pterodactyl accounts?
> > > > > > 
> > > > > > 
> > > > > > Why on earth would you have to fetch 2k accounts while you can just fetch the user's details only?
> > > > > 
> > > > > 
> > > > > To benchmark it, and obv to flex the user count and it fetches everything and makes a dropdown menu (A feature from V0.9)
> > > > 
> > > > 
> > > > Well I do that in the admin routes only. Takes about 20-60ms. >2 ms if users table has less than 5 users.
> > > 
> > > 
> > > Who said that I do it on Users' routes? and your Client is 20x slower than KC V0.5
> > 
> > 
> > I never released HolaClientX publicly, check the #updates if you don't trust.
> 
> I made the calculations based on your answer a few comments up.

We'll see

**Comment by alessiodam** [comment]
Bet my client will be faster, written backend in Rust.

**Comment by BeastGamer81** [comment]
It can never beat KC or HC's speed.

**Comment by privt00** [comment]
Tfc plex speed xD ask coolhigz he said its fast

**Comment by alessiodam** [comment]
> It can never beat KC or HC's speed.

We'll see what rust can do :p

**Comment by nullure** [comment]
Rust is better for heavy software, but for light software like pterodactyl clients. I dont think rust would make much difference while holaclient is reaching a load time of 0.002 and 0ms.

**Comment by alessiodam** [comment]
that's crazy

**Comment by BeastGamer81** [comment]
> > It can never beat KC or HC's speed.
> 
> We'll see what rust can do :p

Okay, we'll see about that.
