### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by codedbean** [HolaClient/X#48]
Hello,

Is the new client still being released  on October 7, 2024?

**Comment by recabasic** [comment]
Yes

**Comment by codedbean** [comment]
Great, thank you for the update.

**Comment by codedbean** [comment]
Is there a demo where I can view the panel or just have to wait for it to be released in October?

**Comment by recabasic** [comment]
Unfortunately, you have to wait till October.

**Comment by codedbean** [comment]
Is the panel delay in the release?

**Comment by recabasic** [comment]
X1 has been postponed to next year, currently I am working on v2, it is meant to fulfill the same purpose as X1 but with minimal features.
